wireplumber.settings.schema = {
  game-target.sink = {
    description = "Sink to route game audio to"
    type = string
    default = ""
  }
  game-target.apps = {
    description = "Comma-separated list of app names to route to game sink"
    type = string
    default = ""
  }
}

# entries can be modified at runtime with `wpctl settings game-target.apps ""`
# however said changes will be lost when wireplumber is restarted
wireplumber.settings = {
  game-target.sink = "alsa_output.usb-TC-Helicon_GoXLRMini-00.HiFi__Line1__sink"
  game-target.apps = "WindowsPlayer.exe,Endfield.exe,MTGA.exe"
}

wireplumber.components = [
  {
    name = "linking/find-game-target.lua"
    type = script/lua
    provides = game-target
  }
]

wireplumber.profiles = {
  main = {
    game-target = required
  }
}
